// Send an old deep link to where its section lives now.
//
// mdbook can redirect a page, and the book's redirect template carries the
// fragment across, but mdbook refuses to redirect a page that still exists. So
// a redirect cannot help when a section moves off a page that stays: every
// link to `basics.html#optional-bridge` then lands at the top of basics, with
// nothing to say the section is elsewhere. This map is the missing half, and the book's anchor check keeps
// the live links honest in the other direction. It also carries a heading
// renamed on its own page when the old id would mislead, such as one that
// gave a time estimate.
//
// An entry maps an old "page.html#fragment" to its new "page.html#fragment",
// relative to the book root. Matching is on the path suffix, so the same entry
// works under /latest/ and under a versioned copy. A re-deployed version is
// built with the current theme, so it runs this map too: an older copy of a
// page that still carries the fragment keeps the reader, because a fragment
// that resolves on the page is never redirected.
(function () {
  "use strict";

  var MOVED = {
    "transformers/common_errors.html#3-method-mapt-cannot-be-applied-on-statet": "transformers/statet_transformer.html#transforming-the-outer-monad-with-mapt",
    "transformers/common_errors.html#4-the-phantom-l-on-eithertfromeither--eitherright": "transformers/common_errors.html#3-the-phantom-l-on-eithertfromeither--eitherright",
    "transformers/common_errors.html#5-cannot-find-symbol-value-on-a-kind": "transformers/common_errors.html#4-cannot-find-symbol-value-on-a-kind",
    "transformers/common_errors.html#6-method-forfrom-is-not-applicable-with-the-wrong-monad": "transformers/common_errors.html#5-method-forfrom-is-not-applicable-with-the-wrong-monad",
    "mapping/basics.html#the-null-contract-precisely": "mapping/rules.html#the-null-contract-precisely",
    "mapping/basics.html#same-typed-containers-cross-as-copies": "mapping/rules.html#same-typed-containers-cross-as-copies",
    "mapping/basics.html#how-the-two-default-families-are-told-apart": "mapping/rules.html#how-the-two-default-families-are-told-apart",
    "mapping/basics.html#derived-fields-and-the-emission-tiers": "mapping/rules.html#derived-fields-and-the-emission-tiers",
    "mapping/structure.html#how-a-dependencys-specs-are-found": "mapping/rules.html#how-a-dependencys-specs-are-found",
    "mapping/codecs.html#admonition-the-inheritance-edge-cases-precisely": "mapping/rules.html#inheriting-one-member-twice",
    "mapping/generics.html#admonition-boundaries": "mapping/rules.html#generic-boundaries",
    "mapping/basics.html#optional-bridge": "mapping/absence.html#optional-bridge",
    "mapping/basics.html#constructor-invariants": "mapping/absence.html#constructor-invariants",
    "mapping/basics.html#the-fine-print": "mapping/basics.html#bind-in-the-caller",
    "mapping/codecs.html#your-own-canon-validatedprismcanonical": "mapping/codecs.html#your-own-canon",
    "mapping/merge_envelopes.html#admonition-fine-grained-or-coarse-variants": "mapping/merge_envelopes.html#fine-grained-or-coarse-variants",
    "mapping/beans_patch.html#bean-shaped-wire-targets": "mapping/beans.html#bean-shaped-wire-targets",
    "mapping/beans_patch.html#bean-projections": "mapping/beans.html#bean-projections",
    "mapping/beans_patch.html#accessors-meant-to-stay-out": "mapping/beans.html#accessors-meant-to-stay-out",
    "mapping/beans_patch.html#one-directional-beans": "mapping/beans.html#one-directional-beans",
    "mapping/compiler_errors.html#private-access-in-an-impl": "mapping/compiler_errors.html#component-cannot-be-reached",
    "mapping/compiler_errors.html#inside-a-generated-impl": "mapping/compiler_errors.html#where-the-message-came-from",
    "release-history.html#v0410-30-august-2026": "release-history/v0_4_10.html#v0410-30-august-2026",
    "release-history.html#v049-31-july-2026": "release-history/v0_4_9.html#v049-31-july-2026",
    "release-history.html#v048-17-july-2026": "release-history/v0_4_8.html#v048-17-july-2026",
    "release-history.html#v047-26-june-2026": "release-history/v0_4_7.html#v047-26-june-2026",
    "release-history.html#v046-7-june-2026": "release-history/v0_4_6.html#v046-7-june-2026",
    "release-history.html#v045-22-may-2026": "release-history/v0_4_5.html#v045-22-may-2026",
    "release-history.html#v044-16-may-2026": "release-history/v0_4_4.html#v044-16-may-2026",
    "release-history.html#v043-7-may-2026": "release-history/v0_4_3.html#v043-7-may-2026",
    "release-history.html#v042-18-april-2026": "release-history/v0_4_2.html#v042-18-april-2026",
    "release-history.html#v041-8-april-2026": "release-history/v0_4_1.html#v041-8-april-2026",
    "release-history.html#v040-22-march-2026": "release-history/v0_4_0.html#v040-22-march-2026",
    "release-history.html#v037-15-march-2026": "release-history/v0_3.html#v037-15-march-2026",
    "release-history.html#v036-6-march-2026": "release-history/v0_3.html#v036-6-march-2026",
    "release-history.html#v035-15-february-2026": "release-history/v0_3.html#v035-15-february-2026",
    "release-history.html#v034-31-january-2026": "release-history/v0_3.html#v034-31-january-2026",
    "release-history.html#v033-24-january-2026": "release-history/v0_3.html#v033-24-january-2026",
    "release-history.html#v032-17-january-2026": "release-history/v0_3.html#v032-17-january-2026",
    "release-history.html#v031-15-january-2026": "release-history/v0_3.html#v031-15-january-2026",
    "release-history.html#v030-4-january-2026": "release-history/v0_3.html#v030-4-january-2026",
    "release-history.html#v028-26-december-2025": "release-history/earlier.html#v028-26-december-2025",
    "release-history.html#v027-20-december-2025": "release-history/earlier.html#v027-20-december-2025",
    "release-history.html#v026-19-december-2025": "release-history/earlier.html#v026-19-december-2025",
    "release-history.html#v025-9-december-2025": "release-history/earlier.html#v025-9-december-2025",
    "release-history.html#v024-3-december-2025": "release-history/earlier.html#v024-3-december-2025",
    "release-history.html#v023-1-december-2025": "release-history/earlier.html#v023-1-december-2025",
    "release-history.html#v022-29-november-2025": "release-history/earlier.html#v022-29-november-2025",
    "release-history.html#v021-23-november-2025": "release-history/earlier.html#v021-23-november-2025",
    "release-history.html#v020-21-november-2025": "release-history/earlier.html#v020-21-november-2025",
    "release-history.html#v019-14-november-2025": "release-history/earlier.html#v019-14-november-2025",
    "release-history.html#v018-9-september-2025": "release-history/earlier.html#v018-9-september-2025",
    "release-history.html#v017-29-august-2025": "release-history/earlier.html#v017-29-august-2025",
    "release-history.html#v016-14-july-2025": "release-history/earlier.html#v016-14-july-2025",
    "release-history.html#v015-12-june-2025": "release-history/earlier.html#v015-12-june-2025",
    "release-history.html#v014-5-june-2025": "release-history/earlier.html#v014-5-june-2025",
    "release-history.html#v013-31-may-2025": "release-history/earlier.html#v013-31-may-2025",
    "release-history.html#v010-3-may-2025": "release-history/earlier.html#v010-3-may-2025",
    "release-history.html#0411-snapshot-latest": "release-history/v0_4_11.html",
    "release-history.html#recent-releases": "release-history.html#releases-at-a-glance",
    "release-history.html#earlier-releases": "release-history/earlier.html",
    "release-history.html#documentation--tutorial-improvements": "release-history/v0_4_4.html#documentation--tutorial-improvements",
    "release-history.html#documentation--tutorial-improvements-1": "release-history/v0_4_3.html#documentation--tutorial-improvements",
    "tutorials/ch_intro.html#fifteen-journeys": "tutorials/ch_intro.html#journeys",
    "tutorials/concurrency/scope_resource_journey.html#tutorial-1-structured-concurrency-with-scope-15-minutes": "tutorials/concurrency/scope_resource_journey.html#tutorial-1-structured-concurrency-with-scope",
    "tutorials/concurrency/scope_resource_journey.html#tutorial-2-resource-management-15-minutes": "tutorials/concurrency/scope_resource_journey.html#tutorial-2-resource-management",
    "tutorials/concurrency/vtask_journey.html#tutorial-1-vtask-fundamentals-25-minutes": "tutorials/concurrency/vtask_journey.html#tutorial-1-vtask-fundamentals",
    "tutorials/concurrency/vtask_journey.html#tutorial-2-vtaskpath-effect-api-20-minutes": "tutorials/concurrency/vtask_journey.html#tutorial-2-vtaskpath-effect-api",
    "tutorials/coretypes/advanced_journey.html#tutorial-08-natural-transformations-10-minutes": "tutorials/coretypes/advanced_journey.html#tutorial-08-natural-transformations",
    "tutorials/coretypes/advanced_journey.html#tutorial-09-coyoneda-10-minutes": "tutorials/coretypes/advanced_journey.html#tutorial-09-coyoneda",
    "tutorials/coretypes/advanced_journey.html#tutorial-10-free-applicative-10-minutes": "tutorials/coretypes/advanced_journey.html#tutorial-10-free-applicative",
    "tutorials/coretypes/advanced_journey.html#tutorial-11-static-analysis-10-minutes": "tutorials/coretypes/advanced_journey.html#tutorial-11-static-analysis",
    "tutorials/coretypes/error_handling_journey.html#tutorial-05-monaderror-handling-10-minutes": "tutorials/coretypes/error_handling_journey.html#tutorial-05-monaderror-handling",
    "tutorials/coretypes/error_handling_journey.html#tutorial-06-concrete-types-10-minutes": "tutorials/coretypes/error_handling_journey.html#tutorial-06-concrete-types",
    "tutorials/coretypes/error_handling_journey.html#tutorial-07-real-world-10-minutes": "tutorials/coretypes/error_handling_journey.html#tutorial-07-real-world",
    "tutorials/coretypes/error_handling_journey.html#tutorial-12-accumulating-assembly-10-minutes": "tutorials/coretypes/error_handling_journey.html#tutorial-12-accumulating-assembly",
    "tutorials/coretypes/foundations_journey.html#tutorial-00-one-line-six-layers-10-minutes": "tutorials/coretypes/foundations_journey.html#tutorial-00-one-line-six-layers",
    "tutorials/coretypes/foundations_journey.html#tutorial-01-kind-basics-10-minutes": "tutorials/coretypes/foundations_journey.html#tutorial-01-kind-basics",
    "tutorials/coretypes/foundations_journey.html#tutorial-02-functor-mapping-10-minutes": "tutorials/coretypes/foundations_journey.html#tutorial-02-functor-mapping",
    "tutorials/coretypes/foundations_journey.html#tutorial-03-applicative-combining-10-minutes": "tutorials/coretypes/foundations_journey.html#tutorial-03-applicative-combining",
    "tutorials/coretypes/foundations_journey.html#tutorial-04-monad-chaining-10-minutes": "tutorials/coretypes/foundations_journey.html#tutorial-04-monad-chaining",
    "tutorials/effect/effect_journey.html#part-1-fundamentals-35-min-9-exercises": "tutorials/effect/effect_journey.html#part-1-fundamentals",
    "tutorials/effect/effect_journey.html#part-2-advanced-35-min-8-exercises": "tutorials/effect/effect_journey.html#part-2-advanced",
    "tutorials/expression/forpath_parallel_journey.html#tutorial-02-forpath-parallel-composition-20-minutes": "tutorials/expression/forpath_parallel_journey.html#tutorial-02-forpath-parallel-composition",
    "tutorials/expression/forstate_journey.html#tutorial-01-forstate-basics-25-minutes": "tutorials/expression/forstate_journey.html#tutorial-01-forstate-basics",
    "tutorials/learning_paths.html#error-mastery-70-min": "tutorials/learning_paths.html#error-mastery",
    "tutorials/learning_paths.html#dsl-power-70-min": "tutorials/learning_paths.html#dsl-power",
    "tutorials/learning_paths.html#effect-api-complete-65-min": "tutorials/learning_paths.html#effect-api-complete",
    "tutorials/learning_paths.html#concurrency-complete-75-min": "tutorials/learning_paths.html#concurrency-complete",
    "tutorials/optics/batching_journey.html#tutorial-21-optic-driven-request-batching-15-minutes": "tutorials/optics/batching_journey.html#tutorial-21-optic-driven-request-batching",
    "tutorials/optics/batching_journey.html#tutorial-22-plan-introspection-and-guardrails-12-minutes": "tutorials/optics/batching_journey.html#tutorial-22-plan-introspection-and-guardrails",
    "tutorials/optics/batching_journey.html#tutorial-23-n-ary-coupled-lenses-10-minutes": "tutorials/optics/batching_journey.html#tutorial-23-n-ary-coupled-lenses",
    "tutorials/optics/boundary_mapping_journey.html#tutorial-24-multi-edit-and-sparse-updates-12-minutes": "tutorials/optics/boundary_mapping_journey.html#tutorial-24-multi-edit-and-sparse-updates",
    "tutorials/optics/boundary_mapping_journey.html#tutorial-25-validatedprism-10-minutes": "tutorials/optics/boundary_mapping_journey.html#tutorial-25-validatedprism",
    "tutorials/optics/boundary_mapping_journey.html#tutorial-26-record-mapping-12-minutes": "tutorials/optics/boundary_mapping_journey.html#tutorial-26-record-mapping",
    "tutorials/optics/boundary_mapping_journey.html#tutorial-27-boundary-edge-cases-15-minutes": "tutorials/optics/boundary_mapping_journey.html#tutorial-27-boundary-edge-cases",
    "tutorials/optics/fluent_free_journey.html#tutorial-09-fluent-optics-api-10-minutes": "tutorials/optics/fluent_free_journey.html#tutorial-09-fluent-optics-api",
    "tutorials/optics/fluent_free_journey.html#tutorial-10-advanced-prism-patterns-10-minutes": "tutorials/optics/fluent_free_journey.html#tutorial-10-advanced-prism-patterns",
    "tutorials/optics/fluent_free_journey.html#tutorial-11-free-monad-dsl-15-minutes": "tutorials/optics/fluent_free_journey.html#tutorial-11-free-monad-dsl",
    "optics/focus_dsl.html#five-minute-focus-dsl": "optics/focus_dsl.html#the-whole-feature-on-one-screen",
    "tutorials/optics/focus_dsl_journey.html#tutorial-12-focus-dsl-basics-10-minutes": "tutorials/optics/focus_dsl_journey.html#tutorial-12-focus-dsl-basics",
    "tutorials/optics/focus_dsl_journey.html#tutorial-13-advanced-focus-dsl-10-minutes": "tutorials/optics/focus_dsl_journey.html#tutorial-13-advanced-focus-dsl",
    "tutorials/optics/focus_dsl_journey.html#tutorial-19-navigator-generation-10-minutes": "tutorials/optics/focus_dsl_journey.html#tutorial-19-navigator-generation",
    "tutorials/optics/focus_dsl_journey.html#tutorial-20-container-navigation-5-minutes": "tutorials/optics/focus_dsl_journey.html#tutorial-20-container-navigation",
    "tutorials/optics/lens_prism_journey.html#tutorial-01-lens-basics-10-minutes": "tutorials/optics/lens_prism_journey.html#tutorial-01-lens-basics",
    "tutorials/optics/lens_prism_journey.html#tutorial-02-lens-composition-10-minutes": "tutorials/optics/lens_prism_journey.html#tutorial-02-lens-composition",
    "tutorials/optics/lens_prism_journey.html#tutorial-03-prism-basics-10-minutes": "tutorials/optics/lens_prism_journey.html#tutorial-03-prism-basics",
    "tutorials/optics/lens_prism_journey.html#tutorial-04-affine-basics-10-minutes": "tutorials/optics/lens_prism_journey.html#tutorial-04-affine-basics",
    "tutorials/optics/traversals_journey.html#tutorial-05-traversal-basics-10-minutes": "tutorials/optics/traversals_journey.html#tutorial-05-traversal-basics",
    "tutorials/optics/traversals_journey.html#tutorial-06-optics-composition-10-minutes": "tutorials/optics/traversals_journey.html#tutorial-06-optics-composition",
    "tutorials/optics/traversals_journey.html#tutorial-07-generated-optics-10-minutes": "tutorials/optics/traversals_journey.html#tutorial-07-generated-optics",
    "tutorials/optics/traversals_journey.html#tutorial-08-real-world-optics-10-minutes": "tutorials/optics/traversals_journey.html#tutorial-08-real-world-optics",
    "tutorials/resilience/resilience_journey.html#tutorial-1-circuit-breaker-10-minutes": "tutorials/resilience/resilience_journey.html#tutorial-1-circuit-breaker",
    "tutorials/resilience/resilience_journey.html#tutorial-2-saga-10-minutes": "tutorials/resilience/resilience_journey.html#tutorial-2-saga",
    "tutorials/resilience/resilience_journey.html#tutorial-3-retry-bulkhead--combined-resilience-10-minutes": "tutorials/resilience/resilience_journey.html#tutorial-3-retry-bulkhead--combined-resilience",
    "tutorials/resilience/resilience_journey.html#tutorial-4-path-api-resilience-10-minutes": "tutorials/resilience/resilience_journey.html#tutorial-4-path-api-resilience",
    "tutorials/transformers/transformers_journey.html#tutorial-01-when-path-isnt-enough-30-min-6-exercises": "tutorials/transformers/transformers_journey.html#tutorial-01-when-path-isnt-enough",
    "tutorials/transformers/transformers_journey.html#tutorial-02-async-with-absence-25-min-5-exercises": "tutorials/transformers/transformers_journey.html#tutorial-02-async-with-absence",
    "tutorials/transformers/transformers_journey.html#tutorial-03-stacking-transformers-15-min-4-exercises": "tutorials/transformers/transformers_journey.html#tutorial-03-stacking-transformers",
    "tutorials/transformers/transformers_journey.html#tutorial-04-polymorphic-capabilities-mtl-30-40-min-14-exercises": "tutorials/transformers/transformers_journey.html#tutorial-04-polymorphic-capabilities-mtl",
    "tutorials/tutorials_intro.html#thirteen-focused-journeys": "tutorials/tutorials_intro.html#focused-journeys",
    "tutorials/tutorials_intro.html#expression-journey": "tutorials/tutorials_intro.html#expression-journeys",
    "tutorials/tutorials_intro.html#practical-fp-4-sessions": "tutorials/tutorials_intro.html#practical-fp",
    "tutorials/tutorials_intro.html#optics-specialist-4-sessions": "tutorials/tutorials_intro.html#optics-specialist",
    "tutorials/tutorials_intro.html#full-curriculum-13-sessions": "tutorials/tutorials_intro.html#full-curriculum",
    "optics/ch1_intro.html#which-optic-do-you-need": "optics/decision_trees.html#tree-1-which-optic-do-i-need",
    "optics/ch2_intro.html#which-optic-do-you-need": "optics/decision_trees.html#tree-1-which-optic-do-i-need",
    "optics/ch2_intro.html#traversal-vs-fold": "optics/optic_capabilities.html#method-support",
    "optics/ch3_intro.html#which-tool-do-you-need": "optics/decision_trees.html#tree-3-which-advanced-feature",
    "optics/ch3_intro.html#filtering-in-action": "optics/filtered_optics.html#three-ways-to-filter",
    "optics/ch3_intro.html#indexed-access": "optics/indexed_optics.html#the-three-indexed-optics",
    "optics/ch4_intro.html#which-api-should-i-use": "optics/decision_trees.html#tree-2-which-api-style",
    "optics/ch5_intro.html#which-optic-do-i-need": "optics/decision_trees.html#tree-1-which-optic-do-i-need",
    "optics/ch5_intro.html#the-complete-pipeline": "optics/composing_optics.html#the-scenario-validating-user-permissions",
    "optics/advanced_prism_patterns.html#advanced-plugin-composition": "optics/advanced_prism_patterns.html#advanced-plugin-batches",
    "optics/affine.html#think-of-affines-like": "optics/affine.html",
    "optics/auditing_complex_data_example.html#think-of-this-problem-like": "optics/auditing_complex_data_example.html#the-challenge-a-conditional-config-audit",
    "optics/common_data_structure_traversals.html#think-of-structure-traversals-like": "optics/common_data_structure_traversals.html#how-many-values-each-one-reaches",
    "optics/composing_optics.html#think-of-this-composition-like": "optics/composing_optics.html#building-the-path-step-by-step",
    "optics/each_typeclass.html#think-of-each-like": "optics/each_typeclass.html",
    "optics/filtered_optics.html#think-of-filtered-optics-like": "optics/filtered_optics.html#the-scenario-customer-segmentation-in-a-saas-platform",
    "optics/folds.html#think-of-folds-like": "optics/folds.html#the-scenario-analysing-e-commerce-orders",
    "optics/folds.html#think-of-maybe-based-extensions-like": "optics/folds.html#the-challenge-working-with-nullable-values",
    "optics/getters.html#think-of-getters-like": "optics/getters.html",
    "optics/getters.html#think-of-getmaybe-like": "optics/getters.html#the-challenge-null-safe-navigation",
    "optics/indexed_optics.html#think-of-indexed-optics-like": "optics/indexed_optics.html#the-scenario-e-commerce-order-processing",
    "optics/iso.html#think-of-isos-like": "optics/iso.html#the-scenario-translating-between-equivalent-types",
    "optics/limiting_traversals.html#think-of-limiting-traversals-like": "optics/limiting_traversals.html#the-scenario-product-catalogue-management",
    "optics/prisms.html#think-of-prisms-like": "optics/prisms.html#the-scenario-working-with-json-like-data",
    "optics/profunctor_optics.html#think-of-profunctor-adaptations-like": "optics/profunctor_optics.html#the-challenge-type-mismatch-in-real-systems",
    "optics/setters.html#think-of-setters-like": "optics/setters.html",
    "optics/string_traversals.html#think-of-string-traversals-like": "optics/string_traversals.html",
    "optics/traversals.html#think-of-traversals-like": "optics/traversals.html#the-scenario-updating-an-entire-league",
    "optics/traversals.html#think-of-partsof-like": "optics/traversals.html#list-manipulation-with-partsof",
    "optics/kind_field_support.html#automatic-traversal-for-higher-kinded-type-fields": "optics/kind_field_support.html",
    "optics/core_type_integration.html#prisms-and-traversals-for-maybe-either-validated-and-try": "optics/core_type_integration.html",
    "optics/optics_extensions.html#error-handling-for-lens-and-traversal": "optics/optics_extensions.html",
    "optics/optics_spec_interfaces.html#spec-interfaces-for-jackson-and-beyond": "optics/optics_spec_interfaces.html",
    "optics/copy_strategies.html#copy-strategies-for-builder-based-types": "optics/copy_strategies.html",
    "optics/focus_external_bridging.html#bridging-fluent-navigation-into-immutables-lombok-and-beyond": "optics/focus_external_bridging.html",
    "optics/validated_prism.html#the-smart-constructor-optic-a-prism-whose-match-says-why-not-and-all-the-reasons-at-once": "optics/validated_prism.html",
    "optics/optic_batching.html#eliminating-n1-at-the-optic-seam": "optics/optic_batching.html",
    "optics/optic_batching_guardrails.html#knowing-what-an-optic-run-would-do-before-it-does-it": "optics/optic_batching_guardrails.html",
    "optics/cookbook.html#recipe-1-updating-nested-optional-fields": "optics/cookbook.html#optional-field",
    "optics/cookbook.html#recipe-2-modifying-a-specific-variant-of-a-sum-type": "optics/cookbook.html#one-variant",
    "optics/cookbook.html#recipe-3-bulk-updates-across-collections": "optics/cookbook.html#matching-elements",
    "optics/cookbook.html#recipe-4-extracting-values-from-polymorphic-structures": "optics/cookbook.html#variants-in-a-list",
    "optics/cookbook.html#recipe-5-safe-map-access-with-fallback": "optics/cookbook.html#map-entry",
    "optics/cookbook.html#recipe-6-composing-multiple-validations": "optics/cookbook.html#patch",
    "optics/cookbook.html#recipe-7-transforming-nested-collections": "optics/cookbook.html#every-element",
    "optics/cookbook.html#recipe-8-conditional-updates-based-on-related-data": "optics/cookbook.html#matching-elements",
    "optics/cookbook.html#recipe-9-working-with-either-for-error-handling": "optics/cookbook.html#either-field",
    "optics/cookbook.html#recipe-10-sorting-or-reversing-traversed-elements": "optics/cookbook.html#sort",
    "optics/cookbook.html#best-practices": "optics/production_readiness.html#team-conventions-that-work",
    "optics/cookbook.html#1-create-reusable-optic-constants": "optics/production_readiness.html#caching-optics",
    "optics/cookbook.html#2-use-direct-composition-methods": "optics/composition_rules.html#composition-rules-table",
    "optics/cookbook.html#3-document-complex-compositions": "optics/production_readiness.html#team-conventions-that-work",
    "optics/cookbook.html#4-prefer-specific-types-when-available": "optics/decision_trees.html#tree-1-which-optic-do-i-need",
    "optics/cookbook.html#recipe-10b-extracting-values-from-multiple-paths": "optics/cookbook.html#several-places",
    "optics/cookbook.html#recipe-10c-traversal-derived-folds-for-read-only-queries": "optics/cookbook.html#totals",
    "optics/cookbook.html#focus-dsl-recipes": "optics/cookbook.html#find-your-recipe",
    "optics/cookbook.html#recipe-11-nested-record-updates-with-focus-dsl": "optics/cookbook.html#every-element",
    "optics/cookbook.html#recipe-12-sum-type-handling-with-instanceof": "optics/cookbook.html#variants-in-a-list",
    "optics/cookbook.html#recipe-13-generic-collection-traversal-with-traverseover": "optics/focus_effects.html#generic-collection-traversal-with-traverseover",
    "optics/cookbook.html#recipe-14-validation-pipelines-with-modifyf": "optics/cookbook.html#check-values",
    "optics/cookbook.html#recipe-15-aggregation-with-foldmap": "optics/cookbook.html#totals",
    "optics/cookbook.html#recipe-16-debugging-complex-paths-with-traced": "optics/cookbook.html#trace",
    "optics/cookbook.html#recipe-17-conditional-updates-with-modifywhen": "optics/cookbook.html#matching-elements",
    "optics/auditing_complex_data_example.html#a-real-world-deep-dive-into-conditional-config-auditing": "optics/auditing_complex_data_example.html",
    "optics/free_monad_dsl.html#optic-operations-as-data-you-can-inspect-replay-and-refuse": "optics/free_monad_dsl.html",
    "optics/interpreters.html#one-program-several-answers": "optics/interpreters.html",
    "optics/importing_optics.html#extending-your-reach-beyond-your-own-code": "optics/importing_optics.html",
    "optics/affine.html#performance-notes": "optics/production_readiness.html#prisms-and-affines",
    "optics/auditing_complex_data_example.html#performance-notes": "optics/production_readiness.html#runtime-cost",
    "optics/filtered_optics.html#performance-notes": "optics/production_readiness.html#collection-optics",
    "optics/common_data_structure_traversals.html#performance-notes": "optics/production_readiness.html#collection-optics",
    "optics/composing_optics.html#performance-notes": "optics/production_readiness.html#runtime-cost",
    "optics/indexed_access.html#performance-considerations": "optics/production_readiness.html#collection-optics",
    "optics/string_traversals.html#performance-notes": "optics/production_readiness.html#collection-optics",
    "optics/iso.html#performance-notes": "optics/production_readiness.html#caching-optics",
    "optics/lenses.html#performance-notes": "optics/production_readiness.html#what-set-and-modify-allocate",
    "optics/indexed_optics.html#performance-notes": "optics/production_readiness.html#collection-optics",
    "optics/traversals.html#performance-notes": "optics/production_readiness.html#traversal-allocation",
    "optics/traversals.html#performance-considerations": "optics/production_readiness.html#collection-optics",
    "optics/prisms.html#performance-notes": "optics/production_readiness.html#prisms-and-affines",
    "optics/getters.html#performance-considerations": "optics/production_readiness.html#read-cost",
    "optics/getters.html#performance-considerations-1": "optics/production_readiness.html#read-cost",
    "optics/setters.html#performance-considerations": "optics/production_readiness.html#collection-optics",
    "optics/setters.html#optimised-collection-operations": "optics/production_readiness.html#collection-optics",
    "optics/limiting_traversals.html#performance-notes": "optics/production_readiness.html#collection-optics",
    "optics/folds.html#performance-considerations": "optics/production_readiness.html#read-cost",
    "optics/folds.html#performance-notes": "optics/production_readiness.html#read-cost",
    "optics/profunctor_optics.html#performance-notes": "optics/production_readiness.html#adapters-and-paths",
    "optics/focus_reference.html#performance-considerations": "optics/production_readiness.html#adapters-and-paths",
    "optics/common_data_structure_traversals.html#summary": "optics/common_data_structure_traversals.html",
    "optics/core_type_integration.html#summary": "optics/core_type_integration.html",
    "optics/folds.html#admonition-performance-note": "optics/folds.html#ordering-guarantees",
    "optics/lenses.html#working-with-product-types": "optics/lenses.html",
    "optics/coupled_fields.html#atomic-updates-for-fields-with-shared-invariants": "optics/coupled_fields.html",
    "optics/prisms.html#working-with-sum-types": "optics/prisms.html",
    "optics/prism_toolkit.html#convenience-methods-and-common-patterns-with-the-prisms-utility": "optics/prism_toolkit.html",
    "optics/advanced_prism_patterns.html#real-world-applications-of-prisms-in-production-systems": "optics/advanced_prism_patterns.html",
    "optics/advanced_prism_patterns_recipes.html#optimisation-and-testing-recipes": "optics/advanced_prism_patterns_recipes.html",
    "optics/affine.html#working-with-optional-fields": "optics/affine.html",
    "optics/iso.html#data-equivalence-with-isos": "optics/iso.html",
    "optics/profunctor_optics.html#adapting-optics-to-different-data-types": "optics/profunctor_optics.html",
    "optics/profunctor_optics_recipes.html#wrapper-adapters-migration-recipes-and-a-complete-worked-example": "optics/profunctor_optics_recipes.html",
    "optics/traversals.html#handling-bulk-updates": "optics/traversals.html",
    "optics/folds.html#querying-immutable-data": "optics/folds.html",
    "optics/getters.html#composable-read-only-access": "optics/getters.html",
    "optics/setters.html#composable-write-only-modifications": "optics/setters.html",
    "optics/common_data_structure_traversals.html#extending-traversal-power-to-optional-map-and-tuple-types": "optics/common_data_structure_traversals.html",
    "optics/limiting_traversals.html#declarative-slicing-for-targeted-operations": "optics/limiting_traversals.html",
    "optics/filtered_optics.html#declarative-filtering-for-targeted-operations": "optics/filtered_optics.html",
    "optics/indexed_optics.html#tracking-indices-during-transformations": "optics/indexed_optics.html",
    "optics/indexed_optics_advanced.html#advanced-composition-patterns-and-the-haskell-heritage": "optics/indexed_optics_advanced.html",
    "optics/each_typeclass.html#one-canonical-traversal-per-container": "optics/each_typeclass.html",
    "optics/string_traversals.html#type-safe-text-manipulation-without-regex-complexity": "optics/string_traversals.html",
    "optics/indexed_access.html#crud-and-safe-partial-access-for-collections": "optics/indexed_access.html",
    "optics/prism_toolkit.html#streamlined-operations-for-common-patterns": "optics/prism_toolkit.html#prism-convenience-methods",
    "optics/prism_toolkit.html#ready-made-prisms-for-standard-types": "optics/prism_toolkit.html#common-prism-patterns-with-the-prisms-utility",
    "optics/advanced_prism_patterns.html#type-safe-layered-configuration-resolution": "optics/advanced_prism_patterns.html#pattern-1-configuration-management",
    "optics/advanced_prism_patterns.html#type-safe-http-response-processing": "optics/advanced_prism_patterns.html#pattern-2-api-response-handling",
    "optics/advanced_prism_patterns.html#composable-type-safe-validation-logic": "optics/advanced_prism_patterns.html#pattern-3-data-validation-pipelines",
    "optics/advanced_prism_patterns.html#type-safe-event-routing-and-handling": "optics/advanced_prism_patterns.html#pattern-4-event-processing",
    "optics/advanced_prism_patterns.html#type-safe-state-transitions": "optics/advanced_prism_patterns.html#pattern-5-state-machines",
    "optics/advanced_prism_patterns.html#type-safe-plugin-discovery-and-execution": "optics/advanced_prism_patterns.html#pattern-6-plugin-systems",
    "optics/traversals.html#treating-traversal-focuses-as-collections": "optics/traversals.html#list-manipulation-with-partsof",
    "optics/traversals.html#switching-from-modification-to-aggregation": "optics/traversals.html#converting-to-read-only-folds-with-asfold",
    "optics/ch1_intro.html#chapter-contents": "optics/ch1_intro.html#pages-in-this-group",
    "optics/ch2_intro.html#chapter-contents": "optics/ch2_intro.html#pages-in-this-group",
    "optics/ch3_intro.html#chapter-contents": "optics/ch3_intro.html#pages-in-this-group",
    "optics/ch4_intro.html#chapter-contents": "optics/ch4_intro.html#pages-in-this-group",
    "optics/ch5_intro.html#chapter-contents": "optics/ch5_intro.html#pages-in-this-group",
    "optics/ch6_intro.html#chapter-contents": "optics/ch6_intro.html#pages-in-this-group",
    "optics/ch6_intro.html#which-interpreter-do-you-need": "optics/decision_trees.html#tree-4-which-interpreter",
    "optics/ch7_intro.html#chapter-contents": "optics/ch7_intro.html#look-it-up",
    "optics/focus_dsl.html#the-problem-verbose-manual-composition": "optics/focus_dsl.html#chain-with-via",
    "optics/quickstart.html#1-from-cascade-to-one-liner": "optics/quickstart.html#1-annotate-then-update",
    "optics/optics_intro.html#the-core-idea": "optics/optics_intro.html#each-path-type-wraps-an-optic",
    "optics/optics_intro.html#think-of-optics-like": "optics/optics_intro.html#choosing-an-optic",
    "optics/optics_intro.html#the-optics-family-in-higher-kinded-j": "optics/optics_intro.html#choosing-an-optic",
    "optics/optics_intro.html#1-lens-for-has-a-relationships": "optics/optics_intro.html#what-a-lens-is",
    "optics/optics_intro.html#2-iso-for-is-equivalent-to-relationships": "optics/optics_intro.html#choosing-an-optic",
    "optics/optics_intro.html#3-prism-for-is-a-relationships": "optics/optics_intro.html#choosing-an-optic",
    "optics/optics_intro.html#4-affine-for-might-be-there-relationships": "optics/optics_intro.html#choosing-an-optic",
    "optics/optics_intro.html#5-traversal-for-has-many-relationships": "optics/optics_intro.html#choosing-an-optic",
    "optics/optics_intro.html#6-fold-for-has-many-queries": "optics/optics_intro.html#choosing-an-optic",
    "optics/optics_intro.html#advanced-capabilities-profunctor-adaptations": "optics/profunctor_optics.html#the-three-profunctor-operations",
    "optics/optics_intro.html#how-higher-kinded-j-provides-optics": "optics/fluent_api.html#part-3-arbitrary-effects-with-modifyf",
    "optics/optics_intro.html#common-patterns": "optics/lenses.html#when-to-use-with-helpers-vs-manual-lenses",
    "optics/optics_intro.html#when-to-use-with-helpers-vs-manual-lenses": "optics/lenses.html#when-to-use-with-helpers-vs-manual-lenses",
    "optics/optics_intro.html#decision-guide": "optics/optics_intro.html#choosing-an-optic",
    "optics/optics_intro.html#common-pitfalls": "optics/fluent_api.html#pitfalls",
    "optics/fluent_api.html#the-same-four-as-builders": "optics/fluent_api.html#the-two-styles",
    "optics/composing_optics.html#capstone-composing-optics-for-deep-validation": "optics/composing_optics.html#deep-validation-with-modifyf",
    "optics/optics_intro.html#what-are-optics": "optics/optics_intro.html#what-a-path-is-made-of",
    "optics/fluent_api.html#fluent-api-for-optics-java-friendly-optic-operations": "optics/fluent_api.html#updates-that-can-fail",
    "optics/fluent_api.html#admonition-when-modifyf-is-still-the-right-tool": "optics/fluent_api.html#part-3-arbitrary-effects-with-modifyf",
    "optics/multi_edit.html#multi-edit-and-sparse-updates": "optics/multi_edit.html#many-edits-at-once",
    "optics/multi_edit.html#n-edits-in-one-operation-and-the-rest-patch-shape": "optics/multi_edit.html#many-edits-at-once",
    "optics/focus_dsl.html#think-of-focus-paths-like": "optics/focus_dsl.html#the-whole-feature-on-one-screen",
    "optics/focus_dsl.html#type-safe-navigation-through-nested-data": "optics/focus_dsl.html#the-whole-feature-on-one-screen",
    "optics/focus_effects.html#working-with-sum-types-using-instanceof": "optics/focus_navigation.html#working-with-sum-types-using-instanceof"
  };

  function target() {
    var hash = window.location.hash;
    if (!hash || hash.length < 2) return null;
    var pathname = window.location.pathname;
    for (var from in MOVED) {
      if (!Object.prototype.hasOwnProperty.call(MOVED, from)) continue;
      var split = from.indexOf("#");
      var page = from.slice(0, split);
      var fragment = from.slice(split);
      if (fragment !== hash) continue;
      // The path suffix, so /latest/ and /v0.4.10/ both match.
      if (pathname.slice(-page.length) !== page) continue;
      var root = pathname.slice(0, pathname.length - page.length);
      return root + MOVED[from];
    }
    return null;
  }

  function follow() {
    // A fragment that resolves on this page is not stale, whatever the map says.
    var hash = window.location.hash;
    if (hash && hash.length > 1) {
      var id = decodeURIComponent(hash.slice(1));
      if (document.getElementById(id)) return;
    }
    var moved = target();
    if (moved) window.location.replace(moved);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", follow);
  } else {
    follow();
  }
  window.addEventListener("hashchange", follow);
})();
